version: '2'
services:
  legacy-fpm:
    image: php:7.0-fpm
    volumes:
      - ./legacy:/app
    working_dir: /app
  legacy:
    image: nginx
    volumes:
      - ./legacy/docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./legacy:/app
    links:
      - legacy-fpm
  refonte-fpm:
    image: php:7.0-fpm
    volumes:
      - ./refonte:/app
    working_dir: /app
  refonte:
    image: httpd
    volumes:
      - ./refonte/docker/apache.conf:/usr/local/apache2/conf/000-default.conf
      - ./refonte:/app
    environment:
        VIRTUAL_HOST: refonteapache.docker
    links:
      - refonte-fpm
      - legacy

networks:
  default:
    external:
      name: wyndproject