apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: legacy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: legacy
    spec:
      containers:
      - name: refonte
        image: darkilliant/kubernetes-legacy:latest
        ports:
        - containerPort: 80